### ISSUE TITLE
PBS-Java Setup Question

### ISSUE THREAD

**Issue by rumanali123** [prebid/prebid-server#2291]
i implemented the prebid server. My bidrequest send to the auction but didn't get back to me.

This is printing while using the localhost server
2022-07-06 16:50:22.784  WARN 6424 --- [ntloop-thread-1] .p.s.a.r.Ortb2ImplicitParametersResolver : No IP address found in OpenRTB request and HTTP request headers.
2022-07-06 16:50:22.785  WARN 6424 --- [ntloop-thread-1] .p.s.a.r.Ortb2ImplicitParametersResolver : Error occurred while populating bid request: Cannot derive eTLD+1 for host localhost

this is my prebid code
<html>

<head>
    <link rel="icon" type="image/png" href="/favicon.png">
    <script async src="//www.googletagservices.com/tag/js/gpt.js"></script>
    
    
    
    

    <script async src="prebid_both.js"></script>
    
    

    <script>
        var div_1_sizes = [
            [300, 250]
        ];
        var PREBID_TIMEOUT = 10000;
        var FAILSAFE_TIMEOUT = 10000;
        var adUnits = [{
            code: '***',
            sizes: div_1_sizes,
            mediaTypes: {
                banner: {
                    sizes: div_1_sizes,
                }
            },
            bids: [
                {
                    bidder: 'improvedigital',
                    params: {
                        placementId: ***
                    }
                }
            ]
        }];
        // ======== DO NOT EDIT BELOW THIS LINE =========== //
        var googletag = googletag || {};
        googletag.cmd = googletag.cmd || [];
        googletag.cmd.push(function () {
            googletag.pubads().disableInitialLoad();
        });

        var pbjs = pbjs || {};
        pbjs.que = pbjs.que || [];

        pbjs.que.push(function () {
            pbjs.setConfig({
                debug: true,
                improvedigital: { usePrebidSizes: true },
                s2sConfig: {
                    adapter: 'prebidServer',
                    testing: true,
                    endpoint: "http://localhost:8080/openrtb2/auction",
                    // syncEndpoint: 'http://localhost:8080/cookie_sync',
                    // syncEndpoint: syncEndpoint,
                    enabled: true,
                    accountId: '***',
                    bidders: ['improvedigital'],

                    timeout: 1000,
                    extPrebid: {
                        cache: {
                            vastxml: { returnCreative: false }
                        },
                        // targeting: {
                        //     pricegranularity: { "ranges": [{ "max": 40.00, "increment": 0.00 }] }
                        // }
                    },
                }            });
            pbjs.addAdUnits(adUnits);
            pbjs.requestBids({
                bidsBackHandler: initAdserver,
                timeout: PREBID_TIMEOUT
            });

        });

        function initAdserver() {
            console.log("init run hwa hy");
            if (pbjs.initAdserverSet) return;
            pbjs.initAdserverSet = true;
            googletag.cmd.push(function () {
                pbjs.que.push(function () {
                    pbjs.setTargetingForGPTAsync();
                    googletag.pubads().refresh();
                });
            });
        }
        // in case PBJS doesn't load
        setTimeout(function () {
            console.log("prebid didnot load");
            initAdserver();
        }, FAILSAFE_TIMEOUT);

        googletag.cmd.push(function () {
            googletag.defineSlot('***', div_1_sizes, 'div1').addService(googletag.pubads());
            googletag.pubads().enableSingleRequest();
            googletag.enableServices();
        });
        googletag.cmd.push(function () {
            googletag.display('div1');
        });
    </script>
</head>

<body>
    <h2>Basic Prebid.js Example</h2>
    <h5>Div-1</h5>
    <div id='div1'>
        <script type='text/javascript'>

        </script>
    </div>
    <br>

</body>

</html>

**Comment by SyntaxNode** [comment]
This looks like a question about running a PBS-Java server. That would best be addressed by @bretg.

**Comment by bretg** [comment]
> Cannot derive eTLD+1 for host localhost

It doesn't like being run as localhost. Please try setting up a local /etc/hosts entry like "localhost.mydomain.com"

**Comment by rumanali123** [comment]
<img width="1440" alt="Screenshot 2022-07-07 at 1 20 42 PM" src="https://user-images.githubusercontent.com/108808183/177726707-b99d9638-0947-4530-933d-c0ddcb45a707.png">

still not working 
i change the local domin

**Comment by bretg** [comment]
Talked with the team more. We think the 'No IP address' warning could appear if the only address PBS can find is loopback -- e.g. 127.0.0.1.

You can test this in 2 ways:

1) use curl to specify a header --header "X-Forwarded-For: 10.10.10.10"
2) run PBS on a host other than your laptop

However, we don't think that this IP warning should be stopping the auction. Please confirm that you actually see the outbound request. i.e. specify the 'test: 1' parameter and note the debug output.

**Comment by bretg** [comment]
@rumanali123 - did you resolve this?

**Comment by bretg** [comment]
Closing this issue. Please re-open with additional detail as needed. The answer is that PBS can't find a name for itself. You need to set up a local /etc/hosts entry that gives it a name like "pbs.example.com"
